# Generated by Django 4.1.1 on 2022-09-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_post_tags_delete_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
