# Generated by Django 4.1.1 on 2022-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
