# Generated by Django 4.1.1 on 2022-10-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_category_category_slug_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="faf75719-9275-4348-b2e1-269eeb2c023b.png",
                upload_to="post/%d/%m/%y",
            ),
        ),
    ]
