# Generated by Django 4.1.1 on 2022-10-02 21:36

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_category",
            field=models.ForeignKey(
                default=post.models.SubCategory.get_sub,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.subcategory",
            ),
        ),
    ]
