# Generated by Django 4.1.1 on 2022-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_bookmarks_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
