# Generated by Django 4.1.1 on 2022-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/images/profile_pics/pngfind.com-placeholder-png-6104451.png",
                null=True,
                upload_to="images/profile_pics",
            ),
        ),
    ]
