# Generated by Django 4.1.1 on 2022-10-11 09:05

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0014_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=post.models.Category.get_cat,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.category",
            ),
        ),
    ]
